<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\City;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            // DKI Jakarta
            ['name' => 'Jakarta Pusat', 'province' => 'DKI Jakarta', 'type' => 'Kota Administrasi'],
            ['name' => 'Jakarta Utara', 'province' => 'DKI Jakarta', 'type' => 'Kota Administrasi'],
            ['name' => 'Jakarta Barat', 'province' => 'DKI Jakarta', 'type' => 'Kota Administrasi'],
            ['name' => 'Jakarta Selatan', 'province' => 'DKI Jakarta', 'type' => 'Kota Administrasi'],
            ['name' => 'Jakarta Timur', 'province' => 'DKI Jakarta', 'type' => 'Kota Administrasi'],
            ['name' => 'Kepulauan Seribu', 'province' => 'DKI Jakarta', 'type' => 'Kabupaten'],

            // Jawa Barat
            ['name' => 'Bandung', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Bogor', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Depok', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Bekasi', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Cimahi', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Tasikmalaya', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Banjar', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Sukabumi', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Cirebon', 'province' => 'Jawa Barat', 'type' => 'Kota'],
            ['name' => 'Bandung Barat', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Bogor', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Bekasi', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Karawang', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Purwakarta', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Subang', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Indramayu', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Cirebon', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Kuningan', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Majalengka', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Sumedang', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Garut', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Tasikmalaya', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Ciamis', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Pangandaran', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Banjar', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Cianjur', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],
            ['name' => 'Sukabumi', 'province' => 'Jawa Barat', 'type' => 'Kabupaten'],

            // Jawa Tengah
            ['name' => 'Semarang', 'province' => 'Jawa Tengah', 'type' => 'Kota'],
            ['name' => 'Surakarta', 'province' => 'Jawa Tengah', 'type' => 'Kota'],
            ['name' => 'Salatiga', 'province' => 'Jawa Tengah', 'type' => 'Kota'],
            ['name' => 'Magelang', 'province' => 'Jawa Tengah', 'type' => 'Kota'],
            ['name' => 'Pekalongan', 'province' => 'Jawa Tengah', 'type' => 'Kota'],
            ['name' => 'Tegal', 'province' => 'Jawa Tengah', 'type' => 'Kota'],
            ['name' => 'Cilacap', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Banyumas', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Purbalingga', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Banjarnegara', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Kebumen', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Purworejo', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Wonosobo', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Magelang', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Boyolali', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Klaten', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Sukoharjo', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Wonogiri', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Karanganyar', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Sragen', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Grobogan', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Blora', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Rembang', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Pati', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Kudus', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Jepara', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Demak', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Semarang', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Temanggung', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Kendal', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Batang', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Pekalongan', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Pemalang', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Tegal', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Brebes', 'province' => 'Jawa Tengah', 'type' => 'Kabupaten'],

            // DI Yogyakarta
            ['name' => 'Yogyakarta', 'province' => 'DI Yogyakarta', 'type' => 'Kota'],
            ['name' => 'Sleman', 'province' => 'DI Yogyakarta', 'type' => 'Kabupaten'],
            ['name' => 'Bantul', 'province' => 'DI Yogyakarta', 'type' => 'Kabupaten'],
            ['name' => 'Kulon Progo', 'province' => 'DI Yogyakarta', 'type' => 'Kabupaten'],
            ['name' => 'Gunung Kidul', 'province' => 'DI Yogyakarta', 'type' => 'Kabupaten'],

            // Jawa Timur
            ['name' => 'Surabaya', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Malang', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Kediri', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Blitar', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Mojokerto', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Madiun', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Pasuruan', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Probolinggo', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Batu', 'province' => 'Jawa Timur', 'type' => 'Kota'],
            ['name' => 'Pacitan', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Ponorogo', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Trenggalek', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Tulungagung', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Blitar', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Kediri', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Malang', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Lumajang', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Jember', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Banyuwangi', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Bondowoso', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Situbondo', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Probolinggo', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Pasuruan', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Sidoarjo', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Mojokerto', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Jombang', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Nganjuk', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Madiun', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Magetan', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Ngawi', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Bojonegoro', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Tuban', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Lamongan', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Gresik', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Bangkalan', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Sampang', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Pamekasan', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],
            ['name' => 'Sumenep', 'province' => 'Jawa Timur', 'type' => 'Kabupaten'],

            // Banten
            ['name' => 'Serang', 'province' => 'Banten', 'type' => 'Kota'],
            ['name' => 'Cilegon', 'province' => 'Banten', 'type' => 'Kota'],
            ['name' => 'Tangerang', 'province' => 'Banten', 'type' => 'Kota'],
            ['name' => 'Tangerang Selatan', 'province' => 'Banten', 'type' => 'Kota'],
            ['name' => 'Pandeglang', 'province' => 'Banten', 'type' => 'Kabupaten'],
            ['name' => 'Lebak', 'province' => 'Banten', 'type' => 'Kabupaten'],
            ['name' => 'Tangerang', 'province' => 'Banten', 'type' => 'Kabupaten'],
            ['name' => 'Serang', 'province' => 'Banten', 'type' => 'Kabupaten'],

            // Bali
            ['name' => 'Denpasar', 'province' => 'Bali', 'type' => 'Kota'],
            ['name' => 'Jembrana', 'province' => 'Bali', 'type' => 'Kabupaten'],
            ['name' => 'Tabanan', 'province' => 'Bali', 'type' => 'Kabupaten'],
            ['name' => 'Badung', 'province' => 'Bali', 'type' => 'Kabupaten'],
            ['name' => 'Gianyar', 'province' => 'Bali', 'type' => 'Kabupaten'],
            ['name' => 'Klungkung', 'province' => 'Bali', 'type' => 'Kabupaten'],
            ['name' => 'Bangli', 'province' => 'Bali', 'type' => 'Kabupaten'],
            ['name' => 'Karangasem', 'province' => 'Bali', 'type' => 'Kabupaten'],
            ['name' => 'Buleleng', 'province' => 'Bali', 'type' => 'Kabupaten'],

            // Sumatera Utara
            ['name' => 'Medan', 'province' => 'Sumatera Utara', 'type' => 'Kota'],
            ['name' => 'Binjai', 'province' => 'Sumatera Utara', 'type' => 'Kota'],
            ['name' => 'Tebing Tinggi', 'province' => 'Sumatera Utara', 'type' => 'Kota'],
            ['name' => 'Pematang Siantar', 'province' => 'Sumatera Utara', 'type' => 'Kota'],
            ['name' => 'Tanjung Balai', 'province' => 'Sumatera Utara', 'type' => 'Kota'],
            ['name' => 'Sibolga', 'province' => 'Sumatera Utara', 'type' => 'Kota'],
            ['name' => 'Padang Sidempuan', 'province' => 'Sumatera Utara', 'type' => 'Kota'],
            ['name' => 'Gunungsitoli', 'province' => 'Sumatera Utara', 'type' => 'Kota'],
            ['name' => 'Nias', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Mandailing Natal', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Tapanuli Selatan', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Tapanuli Tengah', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Tapanuli Utara', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Toba Samosir', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Labuhan Batu', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Asahan', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Simalungun', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Dairi', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Karo', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Deli Serdang', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],
            ['name' => 'Langkat', 'province' => 'Sumatera Utara', 'type' => 'Kabupaten'],

            // Sumatera Barat
            ['name' => 'Padang', 'province' => 'Sumatera Barat', 'type' => 'Kota'],
            ['name' => 'Bukittinggi', 'province' => 'Sumatera Barat', 'type' => 'Kota'],
            ['name' => 'Padang Panjang', 'province' => 'Sumatera Barat', 'type' => 'Kota'],
            ['name' => 'Payakumbuh', 'province' => 'Sumatera Barat', 'type' => 'Kota'],
            ['name' => 'Sawahlunto', 'province' => 'Sumatera Barat', 'type' => 'Kota'],
            ['name' => 'Solok', 'province' => 'Sumatera Barat', 'type' => 'Kota'],
            ['name' => 'Pariaman', 'province' => 'Sumatera Barat', 'type' => 'Kota'],
            ['name' => 'Kepulauan Mentawai', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Pesisir Selatan', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Solok', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Sijunjung', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Tanah Datar', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Padang Pariaman', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Agam', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Lima Puluh Kota', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Pasaman', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Solok Selatan', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Dharmasraya', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],
            ['name' => 'Pasaman Barat', 'province' => 'Sumatera Barat', 'type' => 'Kabupaten'],

            // Sumatera Selatan
            ['name' => 'Palembang', 'province' => 'Sumatera Selatan', 'type' => 'Kota'],
            ['name' => 'Prabumulih', 'province' => 'Sumatera Selatan', 'type' => 'Kota'],
            ['name' => 'Pagar Alam', 'province' => 'Sumatera Selatan', 'type' => 'Kota'],
            ['name' => 'Lubuklinggau', 'province' => 'Sumatera Selatan', 'type' => 'Kota'],
            ['name' => 'Ogan Komering Ulu', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Ogan Komering Ilir', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Muara Enim', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Lahat', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Musi Rawas', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Musi Banyuasin', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Banyu Asin', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Ogan Komering Ulu Selatan', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Ogan Komering Ulu Timur', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Ogan Ilir', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Empat Lawang', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Penukal Abab Lematang Ilir', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Musi Rawas Utara', 'province' => 'Sumatera Selatan', 'type' => 'Kabupaten'],

            // Lampung
            ['name' => 'Bandar Lampung', 'province' => 'Lampung', 'type' => 'Kota'],
            ['name' => 'Metro', 'province' => 'Lampung', 'type' => 'Kota'],
            ['name' => 'Lampung Barat', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Tanggamus', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Lampung Selatan', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Lampung Timur', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Lampung Tengah', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Lampung Utara', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Way Kanan', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Tulangbawang', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Pesawaran', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Pringsewu', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Mesuji', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Tulangbawang Barat', 'province' => 'Lampung', 'type' => 'Kabupaten'],
            ['name' => 'Pesisir Barat', 'province' => 'Lampung', 'type' => 'Kabupaten'],

            // Kalimantan Timur
            ['name' => 'Balikpapan', 'province' => 'Kalimantan Timur', 'type' => 'Kota'],
            ['name' => 'Samarinda', 'province' => 'Kalimantan Timur', 'type' => 'Kota'],
            ['name' => 'Bontang', 'province' => 'Kalimantan Timur', 'type' => 'Kota'],
            ['name' => 'Kutai Kartanegara', 'province' => 'Kalimantan Timur', 'type' => 'Kabupaten'],
            ['name' => 'Kutai Barat', 'province' => 'Kalimantan Timur', 'type' => 'Kabupaten'],
            ['name' => 'Kutai Timur', 'province' => 'Kalimantan Timur', 'type' => 'Kabupaten'],
            ['name' => 'Berau', 'province' => 'Kalimantan Timur', 'type' => 'Kabupaten'],
            ['name' => 'Paser', 'province' => 'Kalimantan Timur', 'type' => 'Kabupaten'],
            ['name' => 'Penajam Paser Utara', 'province' => 'Kalimantan Timur', 'type' => 'Kabupaten'],
            ['name' => 'Mahakam Ulu', 'province' => 'Kalimantan Timur', 'type' => 'Kabupaten'],

            // Kalimantan Barat
            ['name' => 'Pontianak', 'province' => 'Kalimantan Barat', 'type' => 'Kota'],
            ['name' => 'Singkawang', 'province' => 'Kalimantan Barat', 'type' => 'Kota'],
            ['name' => 'Sambas', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Bengkayang', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Landak', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Mempawah', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Sanggau', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Ketapang', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Sintang', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Kapuas Hulu', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Sekadau', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Melawi', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Kayong Utara', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],
            ['name' => 'Kubu Raya', 'province' => 'Kalimantan Barat', 'type' => 'Kabupaten'],

            // Kalimantan Selatan
            ['name' => 'Banjarmasin', 'province' => 'Kalimantan Selatan', 'type' => 'Kota'],
            ['name' => 'Banjarbaru', 'province' => 'Kalimantan Selatan', 'type' => 'Kota'],
            ['name' => 'Tanah Laut', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Kota Baru', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Banjar', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Barito Kuala', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Tapin', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Hulu Sungai Selatan', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Hulu Sungai Tengah', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Hulu Sungai Utara', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Tabalong', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Tanah Bumbu', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Balangan', 'province' => 'Kalimantan Selatan', 'type' => 'Kabupaten'],

            // Kalimantan Tengah
            ['name' => 'Palangka Raya', 'province' => 'Kalimantan Tengah', 'type' => 'Kota'],
            ['name' => 'Kotawaringin Barat', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Kotawaringin Timur', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Kapuas', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Barito Selatan', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Barito Utara', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Sukamara', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Lamandau', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Seruyan', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Katingan', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Pulang Pisau', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Gunung Mas', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Barito Timur', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],
            ['name' => 'Murung Raya', 'province' => 'Kalimantan Tengah', 'type' => 'Kabupaten'],

            // Sulawesi Selatan
            ['name' => 'Makassar', 'province' => 'Sulawesi Selatan', 'type' => 'Kota'],
            ['name' => 'Parepare', 'province' => 'Sulawesi Selatan', 'type' => 'Kota'],
            ['name' => 'Palopo', 'province' => 'Sulawesi Selatan', 'type' => 'Kota'],
            ['name' => 'Kepulauan Selayar', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Bulukumba', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Bantaeng', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Jeneponto', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Takalar', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Gowa', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Sinjai', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Maros', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Pangkajene Dan Kepulauan', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Barru', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Bone', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Soppeng', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Wajo', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Sidenreng Rappang', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Pinrang', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Enrekang', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Luwu', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Tana Toraja', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Luwu Utara', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Luwu Timur', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],
            ['name' => 'Toraja Utara', 'province' => 'Sulawesi Selatan', 'type' => 'Kabupaten'],

            // Papua
            ['name' => 'Jayapura', 'province' => 'Papua', 'type' => 'Kota'],
            ['name' => 'Merauke', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Jayawijaya', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Jayapura', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Nabire', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Kepulauan Yapen', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Biak Numfor', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Paniai', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Puncak Jaya', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Mimika', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Boven Digoel', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Mappi', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Asmat', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Yahukimo', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Pegunungan Bintang', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Tolikara', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Sarmi', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Keerom', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Waropen', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Supiori', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Mamberamo Raya', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Nduga', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Lanny Jaya', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Mamberamo Tengah', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Yalimo', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Puncak', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Dogiyai', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Intan Jaya', 'province' => 'Papua', 'type' => 'Kabupaten'],
            ['name' => 'Deiyai', 'province' => 'Papua', 'type' => 'Kabupaten'],
        ];

        DB::table('cities')->insert($cities);
    }
}
